Init cloud connection
Cloud settings found fields:
{'field3': 'CO2', 'field5': 'Light', 'field4': 'TVOC', 'field8': 'Battery level', 'field2': 'Humidity', 'field1': 'Temperature'}
Channel info request succesfull!
Traceback (most recent call last):
  File "/home/pi/SIP/bluepy_scanner_test.py", line 229, in <module>
    main()
  File "/home/pi/SIP/bluepy_scanner_test.py", line 186, in main
    lol=cloud.perse()
AttributeError: 'CloudPost' object has no attribute 'perse'
Init cloud connection
Cloud settings found fields:
{'field5': 'Light', 'field8': 'Battery level', 'field4': 'TVOC', 'field3': 'CO2', 'field1': 'Temperature', 'field2': 'Humidity'}
Channel info request succesfull!
Traceback (most recent call last):
  File "/home/pi/SIP/bluepy_scanner_test.py", line 229, in <module>
    main()
  File "/home/pi/SIP/bluepy_scanner_test.py", line 186, in main
    lol=cloud.perse()
AttributeError: 'CloudPost' object has no attribute 'perse'
Init cloud connection
Cloud settings found fields:
{'field5': 'Light', 'field1': 'Temperature', 'field8': 'Battery level', 'field2': 'Humidity', 'field3': 'CO2', 'field4': 'TVOC'}
Channel info request succesfull!
Traceback (most recent call last):
  File "/home/pi/SIP/bluepy_scanner_test.py", line 229, in <module>
    main()
  File "/home/pi/SIP/bluepy_scanner_test.py", line 186, in main
    lol=cloud.perse()
AttributeError: 'CloudPost' object has no attribute 'perse'
